### ISSUE TITLE
Pandaboard not booting

### ISSUE THREAD

**Issue by madhu2051** [rcn-ee/meta-ti#3]
Hi everyone,

 I was trying to bring-up  the AGL on Pandaboard. With the default yocto layer(meta-ti) in the AGL source code, I was able to generate the target image(agl-image-minimal). When I tried to boot the board with the generated image, the board is not booting and even I didn't see any log on display(blank screen). 
For image flashing, I followed the instructions shared at [](url) .https://maniacbug.wordpress.com/2012/08/03/pandayocto/
Later I tried to build it with the latest poky(denzil-7.0) and meta-ti layers. This time, I am getting some compilation issues something related usage of "gets()" function.
Is there anything, that I am missing?

Thanks in advance.

Regards,
-Madhu.

**Comment by RobertCNelson** [comment]
@madhu2051 this is just a local mirror, for any issues please contact meta-ti upstream..
